export * from './EllipseEighty';
export * from './EllipseEightyOne';
export * from './EllipseEightyTwo';
export * from './EllipseFifty';
export * from './EllipseFiftyEight';
export * from './EllipseFiftyFive';
export * from './EllipseFiftyFour';
export * from './EllipseFiftyNine';
export * from './EllipseFiftyOne';
export * from './EllipseFiftySeven';
export * from './EllipseFiftySix';
export * from './EllipseFiftyThree';
export * from './EllipseFiftyTwo';
export * from './EllipseFortyEight';
export * from './EllipseFortyNine';
export * from './EllipseFortySeven';
export * from './EllipseFortySix';
export * from './EllipsePanda';
export * from './EllipseSeventy';
export * from './EllipseSeventyEight';
export * from './EllipseSeventyFive';
export * from './EllipseSeventyFour';
export * from './EllipseSeventyNine';
export * from './EllipseSeventyOne';
export * from './EllipseSeventySeven';
export * from './EllipseSeventySix';
export * from './EllipseSeventyThree';
export * from './EllipseSeventyTwo';
export * from './EllipseSixty';
export * from './EllipseSixtyEight';
export * from './EllipseSixtyFour';
export * from './EllipseSixtyNine';
export * from './EllipseSixtyOne';
export * from './EllipseSixtySeven';
export * from './EllipseSixtySix';
export * from './EllipseSeventyThree';
export * from './EllipseSixtyTwo';
export * from './EllipseSixtyThree';
export { default as Ellipse46 } from './Ellipse46.png';
export { default as Ellipse47 } from './Ellipse47.png';
export { default as Ellipse48 } from './Ellipse48.png';
export { default as Ellipse49 } from './Ellipse49.png';
export { default as Ellipse50 } from './Ellipse50.png';
export { default as Ellipse52 } from './Ellipse52.png';

