export * from './Info';
export * from './Logo';
export * from './Phone';
export * from './Square';
export * from './Tick';
export * from './UserTick';
export * from './WifiSquare';
export * from './ClipboardTick';
export * from './Subtitle';
export * from './Vector';
export * from './GridFive';
export * from './Teacher';
export * from './BriefCase';
export * from './Home';
export * from './Message'
export * from './Notification'
export * from './Profile'
export * from './ArrowDownSquare'
export * from './ArrowLeftSquare'
export * from './ArrowRightSquare'
export * from './ArrowUpSquare'
export * from './GridFive'
export * from './GridNine'
export * from './GridSix'
export * from './ArrowDownSecond'
export * from './ArrowLeftSecond'
export * from './ArrowRightSecond'
export * from './ArrowUpSecond'
